### ISSUE TITLE
Staff permission management

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#12]
# Staff
* Staff users can have  different rights:
- viewing stats
- approving/deleting either type of user
- creating new staff users

Maybe it is helpful to use the django permissions here or get inspired by other projects?

**Comment by kevihiiin** [comment]
Maybe we can solve issue #6 with this method as well:

There is a decorator where we can specify a specific test which users have to pass in order to get access to the view. We can either use the default one `user_passes_test` and supply a function / check or create a custom one if the check is needed often ([some ideas](https://github.com/match4everyone/match4everything/issues/6#issuecomment-636323398))

I would suggest, that we create different "levels of permissions" for the staff users which we then can check.

For reference 
https://docs.djangoproject.com/en/3.0/topics/auth/default/#limiting-access-to-logged-in-users-that-pass-a-test

**Comment by feeds** [comment]
Yes, I think thats a very easy way to go. @maltezacharias kept mentioning the django permission framework

Scroll to
Permissions and Authorization¶ or groups in [here](https://docs.djangoproject.com/en/3.0/topics/auth/default/)

this could also be a way

**Comment by bjrne** [comment]
It will probably be a join of these methods, there is a special case prepared by django for the `user_passes-test` since we're obviously not the first to implement this behaviour :wink: See https://docs.djangoproject.com/en/3.0/topics/auth/default/#the-permission-required-decorator

I will create a draft PR for this as a proof-of-concept.

**Comment by feeds** [comment]
Closed by #23 @bjrne ?

**Comment by bjrne** [comment]
Yes!
