### ISSUE TITLE
Code and usage documentation

### ISSUE THREAD

**Issue by kevihiiin** [match4everyone/match4everything#41]
Generate code and usage documentation to make contributing and using m4e easier. 
I suggest we use the following:
- Generate the documentation: [sphix](https://www.sphinx-doc.org/en/master/)
- Hosting of documentation: [readthedocs](https://readthedocs.org)
- Docstring style: Either numpy or google style (comparison [here](https://stackoverflow.com/a/24385103/9356180))
- Avoid GitHub Wiki (readthedocs supports selecting specific documentation versions / releases)

Differentiation from README:
@bjrne issue #33 describes an overview page and how to get started (demo, installing m4e)
The readthedocs documentation describes how to set up m4e and how the code works

**Comment by bjrne** [comment]
Sounds great! Out of curiosity, why not the reST-style that is also mentioned in the link? They state that it is recommended by PEP287. I agree that it is not that readable in code, but isn't the point of a generated documentation that the definition lies close to the code, but the viewing takes place in a better formatted style either way?

**Comment by kevihiiin** [comment]
You are right, reST-style seems to be the default now. I think reST might be easier to write (less formatting and boilerplate than e.g. numpy style), but the other styles are easier to read.
My thoughts about the other styles were that when you are writing code, you might want to check what a function does or needs without having to look it up in the online documentation.
But if that is not of much concern, we might as well just stick to PEP287 and use the reST-style.

**Comment by Baschdl** [comment]
We should optimize for readability in the code as no one uses our platform as a "normal python package" and only searches the right methods to call.

**Comment by bjrne** [comment]
That is the question! Regarding #25, being a plugin seems like a viable option...

When a file is 500+ loc, I strongly dislike long documentation strings. But maybe in that case, the problem lies elsewhere :wink:. With the heavier use of class based views in their own files, the longer more readable docstring sounds like a nice choice.

**Comment by feeds** [comment]
I would also favor class doc strings in the code with the small files. 

I agree with @Baschdl - I do not think it is necessary to generate a read-the-docs, since we do not really provide a framework but I would rather concentrate on a detailed setup explanation. ( @kevihiiin  And I don't even know if the doc generation with the mentioned frameworks would work considering the amount of meta code required for the duality of our participants.)

**Comment by Baschdl** [comment]
You mean that someone would use use as an package in their system? Django-cms "plugins" are another thing, if you mean them.

**Comment by kevihiiin** [comment]
I think read-the-docs is still a good way to document the details and the configuration in our project even if we don't use it to document the code itself.
The code will change a lot and so will the configuration and documentation. The built in version selector (e.g. based on releases) makes it easier to find the documentation which is specific to the version a user might be currently running.

**Comment by Baschdl** [comment]
@kevihiiin So you wouldn't generate any documentation directly out of our code?

**Comment by Baschdl** [comment]
I will do the initial setup for sphinx and readthedocs
